//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApproveApi.Models.WebApvModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebApproveEntities : DbContext
    {
        public WebApproveEntities()
            : base("name=WebApproveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
    
        public virtual ObjectResult<sp_RegisterInsert_Result> sp_RegisterInsert(string schemaName, string schema, string targetNameSpace, string transform)
        {
            var schemaNameParameter = schemaName != null ?
                new ObjectParameter("schemaName", schemaName) :
                new ObjectParameter("schemaName", typeof(string));
    
            var schemaParameter = schema != null ?
                new ObjectParameter("Schema", schema) :
                new ObjectParameter("Schema", typeof(string));
    
            var targetNameSpaceParameter = targetNameSpace != null ?
                new ObjectParameter("targetNameSpace", targetNameSpace) :
                new ObjectParameter("targetNameSpace", typeof(string));
    
            var transformParameter = transform != null ?
                new ObjectParameter("Transform", transform) :
                new ObjectParameter("Transform", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RegisterInsert_Result>("sp_RegisterInsert", schemaNameParameter, schemaParameter, targetNameSpaceParameter, transformParameter);
        }
    
        public virtual ObjectResult<sp_RegisterSelect_Result> sp_RegisterSelect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RegisterSelect_Result>("sp_RegisterSelect");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CheckUnApprove()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CheckUnApprove");
        }
    
        public virtual ObjectResult<sp_DocDetailSelect_Result> sp_DocDetailSelect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DocDetailSelect_Result>("sp_DocDetailSelect");
        }
    
        public virtual int sp_DocDetailInsert(string subjectName, string dataRequest, Nullable<System.DateTime> dateRequest, string empId, string statusId)
        {
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("subjectName", subjectName) :
                new ObjectParameter("subjectName", typeof(string));
    
            var dataRequestParameter = dataRequest != null ?
                new ObjectParameter("dataRequest", dataRequest) :
                new ObjectParameter("dataRequest", typeof(string));
    
            var dateRequestParameter = dateRequest.HasValue ?
                new ObjectParameter("dateRequest", dateRequest) :
                new ObjectParameter("dateRequest", typeof(System.DateTime));
    
            var empIdParameter = empId != null ?
                new ObjectParameter("empId", empId) :
                new ObjectParameter("empId", typeof(string));
    
            var statusIdParameter = statusId != null ?
                new ObjectParameter("statusId", statusId) :
                new ObjectParameter("statusId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DocDetailInsert", subjectNameParameter, dataRequestParameter, dateRequestParameter, empIdParameter, statusIdParameter);
        }
    
        public virtual int sp_EmpPermissionInsert(Nullable<int> regId, string groupPermission)
        {
            var regIdParameter = regId.HasValue ?
                new ObjectParameter("regId", regId) :
                new ObjectParameter("regId", typeof(int));
    
            var groupPermissionParameter = groupPermission != null ?
                new ObjectParameter("groupPermission", groupPermission) :
                new ObjectParameter("groupPermission", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EmpPermissionInsert", regIdParameter, groupPermissionParameter);
        }
    }
}
